# Generated by Django 4.2.5 on 2023-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Стоимость')),
                ('image', models.CharField(max_length=255, verbose_name='Изображение')),
                ('release_date', models.DateField(null=True, verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(null=True, verbose_name='Поддержка LTE')),
                ('slug', models.SlugField(unique=True, verbose_name='Слизняк :)')),
            ],
        ),
    ]
